### PR TITLE
Add Audio::Scan 1.08

### PR DESCRIPTION
**Pull request by ralph-irving**

### CODE REVIEW

**Comment by michaelherger** [comment]
According to your mail the bulk of the changes in here is related to Strawberry Perl compatibility? Is there any good reason to update 1.06 with 1.08 on some of the other platforms?

**Comment by mherger** [comment]
Thanks!

**Comment by ralph-irving** [comment]
> According to your mail the bulk of the changes in here is related to Strawberry Perl compatibility? Is there any good reason to update 1.06 with 1.08 on some of the other platforms?

In addition to the changes for SBP compatibility, there are 2 fixes.
1. opus: Fix parsing large comment headers (such as large embedded images) (1.07)
2. mp4: Handle small and zero length atoms. (1.08)
Neither are critical perhaps we can let the windows users shake down 1.08 before upgrading the other platforms?

**Comment by michaelherger** [comment]
Sounds good me. I've already merged the Windows binaries.

**Pull request merged**
