### PR TITLE
Refresh config.guess and config.sub to handle newer architectures

### PR DESCRIPTION
**Pull request by mcdee**
As per #9

### CODE REVIEW

**Comment by gahabana** [comment]
hi @mcdee - thanks for your changes - i have successfully compiled/built LMS server ... had issue with Image.pm in git of the 'slimserver' being 'older' then the .so module built ... but that was one copy and thats all it took !
Am running it on Odroid C2, Armbian (Ubuntu 16.04, all 64bit) and this is then all 64bit setup and seems to be working real well !

can you advise on last remaining piece - binaries for sox/faad/flac are also built but am not sure if LMS server is using them. Could you advice on NAME of the directory within /Bin of LMS server. I think 'aarch64-linux' or maybe 'aarch64-linux-thread-multi' ... or maybe something else. not sure how to check if LMS is using those ... tried some upsampling/downsampling and in process list i can see server starting '/usr/bin/sox' so maybe none of the options i tried works. 
but net is 'build' scripts are not copying those ... and am not sure what name of the folder has to be :)

thank you !

**Review by gahabana — APPROVED** [review]
have tested the changes - on 64bit ARM board (Odroid-C2) - it allows LMS to be built. as well as 3 supporting apps (flac, sox, faad).

**Comment by mherger** [comment]
Rather than download the file over and over again, we could probably include it or download it once and copy where needed? Very much as we do for hints/darwin.pl.

**Comment by gahabana** [comment]
yes agreed - that would be much better. Current versions of those 2 files are dated/updated just now in 2017 whereas those in various build packages are from 2008.
I am not sure what are all the places where they appear ... @mcdee's code changes seem to check/update it during the build process.
e.g. some of the changes would be easy, but would have to be done by maintainer. e.g.  wavpack does have built-in config.guess and config.sub and once those are updated, it builds just fine.
In a same way flac-1.2.1.tar.gz and libogg-1.1.3.tar.gz have those 2 files within them. Same with other tools.
That's for the tools as for the main tree icu4c-4_6-src.tgz contains them as well. 
Michael, would it be a big issue for you to do those updates or you are worried that for some reason it will cause older platforms to stop working/building ?

**Comment by mherger** [comment]
Implemented in commit 4f69d9688ac625fc68c589ca322a52e3b1ee6888

**Pull request closed without merging**
