### PR TITLE
Image::Scale-0.11 is required giflib >= 4.2

### PR DESCRIPTION
**Pull request by t-yoshi**
Image::Scale will be built with:

  JPEG support:     yes (/home/x/slimserver-vendor/CPAN/build/include, libjpeg version 62)
  PNG support:      yes (/home/x/slimserver-vendor/CPAN/build/include, libpng version 1.4.3)
  GIF support:      no, install giflib 4.2 or higher

### CODE REVIEW

**Comment by mherger** [comment]
Alternatively we should update Image::Scale. v0.13 supports older giflib again.

**Comment by fsbruva** [comment]
@mherger, How do you want to handle the resulting .pm change? Put it inside the Perl version dir? Or down in the specific platform/arch directory?

**Comment by mherger** [comment]
I think it would be fine to include it with the specific platform/architecture files. This script usually is run by people with particular needs. We already have done this for Image::Scale in 5.20, where we have some platforms use a more recent version than others.

**Comment by fsbruva** [comment]
Right, but starting in 5.24, v 0.11 is up in the Perl version ditectory. Would you be willing to rebuild & put 0.13 starting in the 5.26 directory?

The larger issue is that in server, we duplicate the Perl version specific .pm files in multiple places. In my testing, it seems Perl is content to load the binary, and then hunt through INC until it finds the appropriate .pm. Doesn't this suggest moving DBI, Class and JSON to a higher level with no negative consequence? This bloats the tarball by 6M, and this will continue to grow by 1.3M for every new Perl. Can we move them out to CPAN/arch/, and have platform-tools omit them for the oddballs that can't handle multiple .pms? Or make an updated_libs folder that we add to INC ?

**Comment by mherger** [comment]
Please see https://github.com/Logitech/slimserver-vendor/issues/35#issuecomment-346038064

**Comment by mherger** [comment]
This request is now obsolete, as we've introduced Image::Scale 0.14

**Pull request closed without merging**
