### PR TITLE
Add flac script for windows msys/mingw32 builds

### PR DESCRIPTION
**Pull request by ralph-irving**
This is the build script used for the flac 1.3.4 binary for windows.

### CODE REVIEW

**Comment by mherger** [comment]
Thanks! That will hopefully help me to get the job done myself in the future :-)

**Comment by ralph-irving** [comment]
I have msys build scripts of all the helper binaries except wmadec as it uses win32 apis that have not been implemented in mingw32.  I'll submit them as I continue to work through the lms win64 port.  Almost all of the scripts and sources had to be tweaked to work with msys64 or remove runtime DLL linkages in favour of static.

**Comment by mherger** [comment]
The latest binaries are all 64-bit only, aren't they?

**Comment by ralph-irving** [comment]
No.  32-bit.  The 64-bit versions are only in my repo https://github.com/ralph-irving/slimserver-win64/tree/master/Bin/MSWin32-x64-multi-thread

**Pull request merged**
