### PR TITLE
make buildme.sh more user-friendly

### PR DESCRIPTION
**Pull request by tomscytale**
- use arg params instead of vars to control sub-builds
- add command line args for tests/clean
- check for required executables and libs

### CODE REVIEW

**Comment by mherger** [comment]
Excellent! That's something I've always wanted to do... Let me review this in a few days.

**Comment by tomscytale** [comment]
thanks

**Comment by mherger** [comment]
you're checking for yasm, but we need nasm. Typo?

**Comment by tomscytale** [comment]
as far as i recall the error message specified yasm.
my history log shows that I installed yasm and the build worked after that.
nasm is not installed on that machine
if you know which module requires the assembler I'll try uninstall yasm and see if i can reproduce

**Comment by mherger** [comment]
yasm is a replacement for nasm. Wouldn't you have a nasm command, probably an alias for yasm or similar?

**Comment by tomscytale** [comment]
nope - the yasm package doesn't provide an alias for nasm

**Comment by mherger** [comment]
That's odd. Because I had to change that line to test for nasm instead of yasm for the script to run. I grepped the folders, too, but only found references to nasm rather than yasm... Will need to run more tests.

**Comment by tomscytale** [comment]
i've uninstalled yasm and am re-running the build
what package needs the assembler?

**Comment by mherger** [comment]
Ok, found it in ffmpeg: it's using yasm if available, falling back to nasm (if available, again). Can you whip up a check for either or?

**Comment by tomscytale** [comment]
done. also added a wrapper for tar to reduce output verbosity

**Comment by mherger** [comment]
Thanks a lot!

**Comment by mherger** [comment]
Ouch... breaks a few things on OSX. Will have to fix that. eg. there's no ldconfig

**Comment by tomscytale** [comment]
don't have OSX myself but I can ask the internet for some
platform-agnostic ways of checking for libraries
what else breaks?

**Comment by mherger** [comment]
The OSX version regex broke due to too many quotes. But that's it so far.

I wrapped the ldconfig call in a check against OSX for now. Would be great if you could fix that for good. Thanks a lot!

**Comment by tomscytale** [comment]
some googling seems to indicate that there isn't a good cross-platform way to check if a library is present. 
i got my present approach from http://serverfault.com/a/513938/87416
another approach is to use `ld` - which should be present on any system that even vaguely resembles UNIX - however according to [this](http://stackoverflow.com/a/1376793/473285) the OSX `ld` doesn't return a useful exit code 
so it looks like we're going to have to use 2 different checks - one for OSX (and i'm still not sure how this can be done on OSX) and one for other unix-like systems (I think `ldconfig` should work on FreeBSD too)

**Pull request merged**
