### PR TITLE
Added fixes to buildme.sh to enable building on FreeBSD

### PR DESCRIPTION
**Pull request by phaethon**
I had to make several changes to build on my Freebsd 10.1 amd64:
- use different flag for ldconfig (-r instead of -p)
- enforce --disable-mmx
- use the same patch for db51 as for OSX

There are still issues with libmediascan, but at least it builds and works (except for photo and video media, which are not so essential).

### CODE REVIEW

**Comment by phaethon** [comment]
Added additionally the FreeBSD fix for libmediascan

**Comment by mherger** [comment]
Unfortunately Andy has been rather quiet recently. I'll see about merging the changes. Thanks!

**Comment by mherger** [comment]
Could you please provide your libmediascan change as a patch and apply it from the script, instead of submitting a new tarball? I'd prefer to stick with the original files and apply patches while building, rather than modify existing files and potentially create multiple, different copies of the same thing.

**Comment by phaethon** [comment]
OK, changed to a patch.

**Pull request merged**
